### ISSUE TITLE
Change *-provider to *-src

### ISSUE THREAD

**Issue by IvanUkhov** [cmr/openblas-src#13]
@cmr, what do you say if we change the naming scheme from `*-provider` to `*-src`? It doesn’t change the essence, of course, but it’s much shorter, goes along with the `*-sys` convention, and conveys well what the crates do. One can also think of `src` as source in general, not necessarily source code. I personally like clean, concise, consistent, and logical naming conventions, and you probably too.

If you support this, please rename both repos, and I’ll do the rest.

**Comment by cmr** [comment]
I don't remember the reasoning for not using `*-sys` for these... do you remember? Since these use the `links =` flag with Cargo, it makes sense for them to be `*-sys` I think. There's a precedent for `*-sys` crates building the library if it isn't present already, too.

**Comment by IvanUkhov** [comment]
The provider crates came about, because there was a need to separate function declarations from linkage: one single set of functions, but three different backends (Accelerate, OpenBLAS, and Netlib). The idea behind a different naming scheme is to suggest that they have no functions and are not useful on their own. Moreover, the documentation [says](http://doc.crates.io/build-script.html#-sys-packages) that `libfoo-sys` provides declarations for functions in `libfoo`; so, technically, our providers don’t qualify as `*-sys` crates. To be strict, the documentation also says that `libfoo-sys` links to the native library `libfoo`, which our `*-sys` creates don’t.

**Comment by cmr** [comment]
Right right, thanks for the reminder. I'm happy with `*-src`.

**Comment by cmr** [comment]
Renamed both!
